apiVersion: v1
kind: Pod
metadata:
  name: script-helper2
#  namespace: latency
spec:
  securityContext:
    runAsUser: 1000  # Menjalankan pod sebagai user 1000
    runAsNonRoot: true  # Memastikan tidak berjalan sebagai root
  containers:
  - name: script-helper
    image: hiroominan/ubuntu:latency
    command: ["/bin/sh", "-c", "sleep infinity"]  # Agar tetap berjalan
    securityContext:
      allowPrivilegeEscalation: false  # Mencegah eskalasi privilege
      runAsUser: 1000  # Menjalankan container sebagai user 1000
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: kubernetes.io/hostname
#            operator: In
#            values:
#            - jah1af11srhgxs022
#      capabilities:
#        add: ["NET_RAW"]
#        add:
#          - NET_RAW
#        drop:
#        - ALL  # Menghapus semua kemampuan khusus untuk keamanan
#    volumeMounts:
#    - name: pvc-script
#      mountPath: "/data"
#  volumes:
#  - name: pvc-script
#    persistentVolumeClaim:
#      claimName: pvc-script
