apiVersion: v1
kind: Pod
metadata:
  name: script-helper
  namespace: default
spec:
  securityContext:
    runAsUser: 1000  # Menjalankan pod sebagai user 1000
    runAsNonRoot: true  # Memastikan tidak berjalan sebagai root
  containers:
  - name: script-helper
    image: hiroominan/ubuntu:latency
    command: ["/bin/sh", "-c", "sleep infinity"]  # Agar tetap berjalan
    securityContext:
      allowPrivilegeEscalation: true  # Mencegah eskalasi privilege
      runAsUser: 1000  # Menjalankan container sebagai user 1000
      capabilities:
        add: ["NET_RAW"]
#        add:
#          - NET_RAW
#        drop:
#        - ALL  # Menghapus semua kemampuan khusus untuk keamanan
    volumeMounts:
    - name: pvc-script
      mountPath: "/data"
  volumes:
  - name: pvc-script
    persistentVolumeClaim:
      claimName: pvc-script
