apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-cronjob
spec:
  schedule: "15 */2 * * *"  # Setiap 5 menit
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: docker
              image: quay.io/skopeo/stable:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  /data/script-docker.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /data
                - name: image-volume
                  mountPath: /data2
#              securityContext:
#                allowPrivilegeEscalation: false
#                runAsUser: 1000
#                capabilities:
#                 drop:
#                 - ALL
#                runAsNonRoot: true
          restartPolicy: Never
          volumes:
            - name: script-volume
              persistentVolumeClaim:
                claimName: pvc-script
            - name: image-volume
              persistentVolumeClaim:
                claimName: pvc-image
