apiVersion: batch/v1
kind: CronJob
metadata:
  name: hping3-cronjob
spec:
  schedule: "*/5 * * * *"  # Setiap 5 menit
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: hping3
              image: hiroominan/ubuntu:latency
              command: ["/bin/sh", "-c"]
              args:
                - |
                  /data/script-hping3.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /data
              securityContext:
                allowPrivilegeEscalation: false
                runAsUser: 1000
                capabilities:
                 drop:
                 - ALL
                runAsNonRoot: true
          restartPolicy: Never
          volumes:
            - name: script-volume
              persistentVolumeClaim:
                claimName: pvc-script
