apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: latency
  labels:
    app: influxdb
  annotations:
    metallb.universe.tf/address-pool: address-pool
spec:
  selector:
    app: influxdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
