apiVersion: batch/v1
kind: CronJob
metadata:
  name: download-cronjob
spec:
  schedule: "0 */2 * * *"  # Setiap 2 jam
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            fsGroup: 1000
          containers:
            - name: download
              image: hiroominan/ubuntu:latency
              command: ["/bin/sh", "-c"]
              args:
                - |
                  /data/script-download.sh
              volumeMounts:
                - name: script-volume
                  mountPath: /data
          restartPolicy: Never
          volumes:
            - name: script-volume
              persistentVolumeClaim:
                claimName: pvc-script
